import Head from "next/head";
import { BuildOrder } from "@prisma/client";
import { useRouter } from "next/router";
import { trpc } from "../../utils/trpc";
import { buildTypes } from "../submit-build";

const BuildPage = () => {
  const router = useRouter();
  const { buildId } = router.query as { buildId: string };

  const build = trpc.builds.getBuildById.useQuery({ buildId });

  return (
    <>
      <Head>
        <title>SC2 Build Order Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container flex justify-center px-8 pt-4 text-black dark:text-white">
        <h1 className="text-3xl">{build.data?.title}</h1>
      </section>
    </>
  );
};

export default BuildPage;
